name: Build and Run KNN R Script in Docker

on:
  push:
    paths:
      - Dockerfile
      - R/**
      - .github/workflows/**
  workflow_dispatch:

jobs:
  knn-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker layer cache
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image with cache
        run: |
          docker build \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            -t knn-r-script .

      - name: Run R script inside Docker container
        run: |
          docker run -v ${{ github.workspace }}:/app -w /app knn-r-script

      - name: Upload plot images
        uses: actions/upload-artifact@v4
        with:
          name: knn-plots
          path: |
            *.png
