name: Run KNN Script

on:
  push:
    paths:
      - 'R/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  run-knn:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Packages
        run: |
          Rscript -e 'options(repos = c(CRAN = "https://cloud.r-project.org"))'
          Rscript -e '
            packages <- c("ISLR", "kknn", "ggplot2", "caret", "dplyr", "gridExtra")
            install_if_missing <- function(pkg) {
              if (!requireNamespace(pkg, quietly = TRUE)) install.packages(pkg)
            }
            invisible(sapply(packages, install_if_missing))
          '

      - name: Run KNN Script
        run: |
          Rscript R/credit_default_pro.R


