name: Run KNN R Script Using Docker Hub Image

on:
  push:
    paths:
      - R/**
      - .github/workflows/**
  workflow_dispatch:

jobs:
  knn-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Pull prebuilt Docker image from Docker Hub
        run: docker pull kwasisarpong/knn-r-script:latest

      - name: Run R script inside Docker container
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/app \
            -w /app \
            kwasisarpong/knn-r-script:latest Rscript R/credit_default_pro.R

      - name: Upload plot images
        uses: actions/upload-artifact@v4
        with:
          name: knn-plots
          path: |
            plots/*.png
