name: Build and Run KNN R Script in Docker

on:
  push:
    paths:
      - Dockerfile
      - R/**
      - .github/workflows/**
  workflow_dispatch:

jobs:
  knn-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t knn-r-script .

      - name: Run R script inside Docker container
        run: |
          docker run -v ${{ github.workspace }}:/app -w /app knn-r-script

      - name: Upload plot images
        uses: actions/upload-artifact@v4
        with:
          name: knn-plots
          path: |
            *.png
